# ~/.sops.yaml
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    age: "age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4"
    mac_only_encrypted: true
    encrypted_regex: "^(data|stringData)$"
stores:
  yaml:
    indent: 2
